version: '3'

services:
  my-node-app:
    build: .
    ports:
      - "5007:5006"
    networks:
      my-network:
        aliases:
          - my-node-container
    healthcheck:
      test: curl --fail http://my-node-container:5006/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
  my-other-container:
    image: navindharmaraj/my-simple-node-app:1.0
    command: sh -c "echo 'Hello from my other container!' && node server.js"
    expose:
    - "5006"
    networks:
      my-network:
        aliases:
          - my-other-container
    healthcheck:
      test: curl --fail http://my-other-container:5006/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  my-network:
    driver: bridge
